[bot]
name = AdamBot
icon = 
public_play = yes
tournaments = no
max_games = 1
token = rps_b_MYru-CoeXFtfcCrBcw61qdLTIEUPMh5t0GVG9ck-3JA
server = wss://api-rps.henhen1227.com/ws
rules_seen = V6:2026-09-03

